function [h1, h2] = solveHandlebarForce(A1,M,L10,L11,L12,L13,P1,P2)
%SOLVEHANDLEBARFORCE This function solves vertical handlebar forces at the
%left and right handlebar during standing cycling using the origin and
%magnitude of forces generated on the pedals, the rider's mass, and
%vertical center of mass acceleration.
%
% Assumption(s):
% 1. There are no forces on the saddle.
% 2. There is no thrust on the bicycle or rider's CoM. (Note: Thrust
% decreases contact force on the rear wheel).
% 3. Aerodynamic forces and rolling resistance are negligible. 
% 4. Weight and inertia of the bicycle itself are neglected. 
% 5. All lateral forces are ignored.
% 6. No attempt to achieve moment equilibrium of the handlebar, brakes, and
% front wheel assembly, which is free to rotate about the steering tube.
% 7. Rider CoM positioned directly above rear-wheel contact.
%
% Inputs: 
% - A1: vertical acceleration of rider's center of mass (m/s^2)
% - M: mass of rider (kg)
% - L10: lateral distance from right pedal to origin (m)
% - L11: lateral distance from left pedal to origin (m)
% - L12: lateral distance from right hand to origin (m)
% - L13: lateral distance from left hand to origin (m)
% - P1: vertical reaction force on right pedal (N)
% - P2: vertical reaction force on left pedal (N)
% Outputs:
% - H1: vertical reaction force on right handlebar (N)
% - H2: vertical reaction force on left handlebar (N)
%
% Equation(s):
% H1 + H2 + P1 + P2 + M * (g+A1) == 0 (Net vertical force == 0)
% H1 * L12 + H2 * L13 + P1 * L10 + P2 * L11 == 0 (Net torque in frontal plane == 0)
%
% Reference coordinates:
% - Right-hand cartesian coordinate system.
% - Origin at point of rear-wheel contact with ground.
% - +x to the right, +y straight up, +z toward viewer.
% - Counter-clockwise torque is +ve when viewing system from the front
% - +torque generated by either upward reaction force at left pedal (++) or
% downward reaction force on right side of right pedal (--)

g = -9.80665;

syms H1 H2
eqnsHv = [H1 + H2 + P1 + P2 + M*(g+A1) == 0, H1*L12 + H2*L13 + P1*L10 + P2*L11 == 0];
[solH1, solH2] = solve(eqnsHv,[H1 H2]);
h1 = double(solH1);
h2 = double(solH2);
        
end

